version: '3'

services:
  mainapp:
    image: daniul/tcmg-group-3-app:latest
    ports:
      - "80:4000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - mynet

  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - mynet

networks:
  mynet:
