name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python AutomatedTest_p2.py
        python AutomatedTest_p3.py

  build_and_push_docker_image:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push multi-platform Docker image
      run: |
        docker buildx create --use
        docker buildx build --no-cache --platform linux/amd64,linux/arm64 -t daniul/tcmg-group-3-app:latest --push .

  deploy_to_gcp:
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - name: Deploy to GCP VM instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.GCP_VM_SSH_KEY }}
        script: |
          docker-compose down
          sudo systemctl restart docker.socket docker.service
          rm -f docker-compose.yml
          wget https://github.com/TCMG-412-Group-3/OurAPI/blob/fb1f4940df5342040cbe4a4ce34aaf707de5b494/docker-compose.yml 
          docker-compose up -d
